spring.application.name=cosmo-cats
spring.web.locale=en
spring.web.locale-resolver=fixed
spring.jackson.deserialization.fail-on-unknown-properties=true
server.port=8080

cosmo.delivery.base-url=http://localhost:8089
cosmo.delivery.connect-timeout=2s
cosmo.delivery.read-timeout=3s
